root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  addons/antivirus: ./security/antivirus.md
  addons/azure-ad: ./security/auth/azure-ad.md
  addons/idporten: ./security/auth/idporten.md
  addons/oauth2-openidconnect: ./security/auth/oauth2-openidconnect.md
  addons/tokenx: ./security/auth/tokenx.md
  addons/secrets: ./security/secrets/README.md
