<script lang="ts">
	import type { Tokens } from "marked";

	let { token }: { token: Tokens.HTML } = $props();

	// Standard HTML elements — anything not in this set is treated as
	// accidental markup (e.g. `<APP>`, `<secret-name>`) and rendered as
	// escaped text so the browser doesn't create unexpected DOM nodes.
	const STANDARD_TAGS = new Set([
		"a",
		"abbr",
		"address",
		"area",
		"article",
		"aside",
		"audio",
		"b",
		"base",
		"bdi",
		"bdo",
		"blockquote",
		"body",
		"br",
		"button",
		"canvas",
		"caption",
		"cite",
		"code",
		"col",
		"colgroup",
		"data",
		"datalist",
		"dd",
		"del",
		"details",
		"dfn",
		"dialog",
		"div",
		"dl",
		"dt",
		"em",
		"embed",
		"fieldset",
		"figcaption",
		"figure",
		"footer",
		"form",
		"h1",
		"h2",
		"h3",
		"h4",
		"h5",
		"h6",
		"head",
		"header",
		"hgroup",
		"hr",
		"html",
		"i",
		"iframe",
		"img",
		"input",
		"ins",
		"kbd",
		"label",
		"legend",
		"li",
		"link",
		"main",
		"map",
		"mark",
		"math",
		"menu",
		"meta",
		"meter",
		"nav",
		"noscript",
		"object",
		"ol",
		"optgroup",
		"option",
		"output",
		"p",
		"param",
		"picture",
		"pre",
		"progress",
		"q",
		"rp",
		"rt",
		"ruby",
		"s",
		"samp",
		"script",
		"search",
		"section",
		"select",
		"slot",
		"small",
		"source",
		"span",
		"strong",
		"style",
		"sub",
		"summary",
		"sup",
		"svg",
		"table",
		"tbody",
		"td",
		"template",
		"textarea",
		"tfoot",
		"th",
		"thead",
		"time",
		"title",
		"tr",
		"track",
		"u",
		"ul",
		"var",
		"video",
		"wbr",
	]);

	function isStandardHtml(html: string): boolean {
		// Match the tag name from opening/closing/self-closing tags
		const tagMatch = html.match(/^<\/?([a-zA-Z][a-zA-Z0-9-]*)/);
		if (!tagMatch) return true; // HTML comments, DOCTYPE, etc.
		return STANDARD_TAGS.has(tagMatch[1].toLowerCase());
	}

	const isStandard = $derived(isStandardHtml(token.text));
</script>

{#if isStandard}
	<!-- eslint-disable-next-line svelte/no-at-html-tags -->
	{@html token.text}
{:else}
	{token.text}
{/if}
