apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}'
  namespace: nais-system
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: '{{ .Release.Name }}'
